Esri/arcgis-maps-sdk-flutter-samples

lib/src/samples/add_feature_layers_sample.dart, lib/src/samples/apply_simple_renderer_to_feature_layer_sample.dart, lib/src/samples/apply_unique_value_renderer_sample.dart, lib/src/samples/filter_by_definition_expression_or_display_filter_sample.dart, lib/src/samples/find_closest_facility_sample.dart, lib/src/samples/identify_layers_sample.dart, lib/src/samples/query_feature_table_sample.dart, lib/src/samples/query_table_statistics_sample.dart, lib/src/samples/select_features_in_feature_layer_sample.dart
The factory constructor `fromUri(Uri)` has been changed to `withUri(Uri)`. This PR updates the uses of the constructor in the samples.
=> Updated ServiceFeatureTable URI constructor calls

lib/src/samples/authenticate_with_oauth_sample.dart
ArcGISExceptionDomain will no longer be part of the public interface.
=> Remove reference to ArcGISExceptionDomain

android/app/src/main/jniLibs/assets/libarcgis_maps_ffi.so, android/app/src/main/jniLibs/assets/libruntimecore.so
These symlinks were erroneously added by `dart run arcgis_maps install`. It incorrectly treated the "assets" folder as one of the hardware architectures. That's been fixed elsewhere, but here we need to remove the bad symlinks that made it into the repo.
=> Remove extraneous symlinks

pubspec.yaml
Upgrade to Flutter 3.22. The only difference was to move the Dart version to 3.4.3 (no deprecations, warnings, etc).
=> Upgrade to Flutter 3.22, which comes with Dart 3.4.3

lib/samples/apply_class_breaks_renderer_to_sublayer/apply_class_breaks_renderer_to_sublayer_sample.dart
Needed to go back and tweak Class breaks renderer to sublayer sample -it had a missing feature that disables the button once the layer is rendered.
=> Apply common sample design to apply class breaks renderer to sublayer

lib/samples/add_feature_collection_layer_from_table/add_feature_collection_layer_from_table_sample.dart, lib/samples/add_feature_layers/add_feature_layers_sample.dart, lib/samples/add_tiled_layer/add_tiled_layer_sample.dart, lib/samples/add_tiled_layer_as_basemap/add_tiled_layer_as_basemap_sample.dart, lib/samples/add_vector_tiled_layer/add_vector_tiled_layer_sample.dart, lib/samples/apply_class_breaks_renderer_to_sublayer/apply_class_breaks_renderer_to_sublayer_sample.dart, lib/samples/apply_scheduled_updates_to_preplanned_map_area/apply_scheduled_updates_to_preplanned_map_area_sample.dart, lib/samples/apply_simple_renderer_to_feature_layer/apply_simple_renderer_to_feature_layer_sample.dart, lib/samples/apply_unique_value_renderer/apply_unique_value_renderer_sample.dart, lib/samples/authenticate_with_oauth/authenticate_with_oauth_sample.dart, lib/samples/display_clusters/display_clusters_sample.dart, lib/samples/display_map_from_mobile_map_package/display_map_from_mobile_map_package_sample.dart, lib/samples/download_preplanned_map_area/download_preplanned_map_area_sample.dart, lib/samples/filter_by_definition_expression_or_display_filter/filter_by_definition_expression_or_display_filter_sample.dart, lib/samples/find_address_with_reverse_geocode/find_address_with_reverse_geocode_sample.dart, lib/samples/find_closest_facility_from_point/find_closest_facility_from_point_sample.dart, lib/samples/find_route/find_route_sample.dart, lib/samples/identify_layer_features/identify_layer_features_sample.dart, lib/samples/query_feature_table/query_feature_table_sample.dart, lib/samples/query_table_statistics/query_table_statistics_sample.dart, lib/samples/search_with_geocode/search_with_geocode_sample.dart, lib/samples/select_features_in_feature_layer/select_features_in_feature_layer_sample.dart, lib/samples/set_basemap/set_basemap_sample.dart, lib/samples/show_device_location/show_device_location_sample.dart, lib/samples/show_device_location_history/show_device_location_history_sample.dart, lib/samples/show_service_area/show_service_area_sample.dart, lib/samples/style_point_with_simple_marker_symbol/style_point_with_simple_marker_symbol_sample.dart, lib/utils/sample_state_support.dart
A new mixin, `SampleStateSupport`, provides an override for "setState" that checks if the widget is still mounted before setting the state. All samples should use `with SampleStateSupport` to get this behaviour transparently.
Also, remove some now-obsolete "mounted" checks.
=> Provide a mixin to resolve "setState called after dispose" exceptions

lib/samples/apply_class_breaks_renderer_to_sublayer/apply_class_breaks_renderer_to_sublayer_sample.dart, lib/samples/display_clusters/display_clusters_sample.dart, lib/samples/find_address_with_reverse_geocode/find_address_with_reverse_geocode_sample.dart, lib/samples/style_point_with_simple_marker_symbol/style_point_with_simple_marker_symbol_sample.dart
In this PR I capture some more of the desired patterns in existing samples.
- Moving setup from `initState` to `onMapViewReady`
- bool -> var
- var -> final/const
I have also checked the following patterns and identified no required changes:
- Use of `Scaffold`, `SafeArea`, `Column`, `Expanded`
- Use of `SafeArea` `top: false`
- class variables with `_`
Affected samples:
- Apply class breaks renderer to sublayer
- display clusters
- find address with reverse geocode
- style point with simple marker symbol
A separate PR will follow to cover use of `ElevatedButton` and `Row.spaceEvenly`
=> Apply patterns to existing samples

lib/samples/add_tiled_layer_as_basemap/add_tiled_layer_as_basemap_sample.dart, lib/samples/apply_class_breaks_renderer_to_sublayer/apply_class_breaks_renderer_to_sublayer_sample.dart, lib/samples/display_clusters/display_clusters_sample.dart, lib/samples/display_map_from_mobile_map_package/display_map_from_mobile_map_package_sample.dart, lib/samples/find_address_with_reverse_geocode/find_address_with_reverse_geocode_sample.dart, lib/samples/find_route/find_route_sample.dart, lib/samples/show_service_area/show_service_area_sample.dart
In this PR I focused on applying progress indicators, or aligning existing progress indicators with our workflow.
It affects:
- Show Service Area
- Find Route
- Find Address With Reverse Geocode
- Display Map From Mobile Map Package
- Display Clusters
- Apply Class Breaks Renderer To Sublayer
- Add Tiled Layer As Basemap
Note that the samples that have not yet had common designs applied we'll come back to once the common design is applied to avoid duplication of effort.
=> Apply progress indicators to samples

lib/samples/show_portal_user_info/README.md
The bulleted lists in the design have `backticks` for formatting. Also, some of the property names are slightly different once they hit the API -- e.g., "thumbnailUrl" is just "thumbnail".
=> Clean up the README for Show Portal User Info

android/app/src/main/AndroidManifest.xml, lib/samples/authenticate_with_oauth/authenticate_with_oauth_sample.dart, lib/samples/show_portal_user_info/show_portal_user_info_sample.dart
Updates to a unique OAuth redirect to avoid clash with other SDK sample viewers on same device. I created a separate OAuth credential so also updates the clientId.
=> Update redirect for OAuth

lib/samples/show_portal_user_info/show_portal_user_info_sample.dart
`LoadableImage` now defines the `loadBytes` function. The extension in the Show portal user info sample is no longer needed.
=> Remove loadable image extension

lib/samples/show_grid/show_grid_sample.dart
Based on the test and feedback of the Sprint Review meeting, Here are some changes made:
- Use enum to hold the list of constant property values
- The changed grid property status is preserved in the UI
- The barrier color is changed to transparent for users to see the changes easily
- The dialog is moved to the bottom center, making more room to view for ArcGISMapView
=> cs/Update Show-grid Sample

lib/samples/query_feature_table/query_feature_table_sample.dart
The 'single quote' is a special character in SQL, so we have to replace them with a pair of single quotes when using user input as part of a `whereClause`.
Also, I reviewed the other SDKs versions of this sample. They use `%` to allow substring matches. So I added a `%` at the end of our query, so that e.g., `Calif` matches `California` and so forth.
=> Escape single quotes in user input

lib/samples/generate_offline_map/generate_offline_map_sample.dart
Judging by the screenshots in the issue, the tester was accidentally rotating the map as they panned and zoomed. Rotating the map led to an incorrect mapping of the red outline envelope to the map. This caused the generated map to be incorrect.
To correct the issue, map rotation was disabled. This is the easiest solution and offline map generation does not take rotation into consideration. The Swift sample app is doing the same.
=> Fix narrow offline maps in Generate offline map sample

lib/samples/download_preplanned_map_area/download_preplanned_map_area_sample.dart
Had the logic upside down, this PR fixes the webmap selection tile.
=> Fix: Download Preplanned Map Area

lib/models/sample.dart, lib/models/samples_widget_list.dart, lib/utils/sample_runner.dart
By lazily instantiating the widgets,  the widgets will be instantiated by demand, it will 
- Speed up the start-up time;
- Reduce the SampleViewer memory usage from 160MB to 130MB (tested on the Android phone).
=> lazily instantiate the widgets

lib/samples/download_vector_tiles_to_local_cache/download_vector_tiles_to_local_cache.dart
disable the map view rotation to avoid the map view becoming 'thin'.
=> Cs/1561 follow up-Disable the map view rotation

tool/generate_new_sample.dart
- Re-adds the comments that explain the file and why the casing is required for future reference.
- Amends the casing of the key to match the json generated_samples_list.
=> Sample generation

assets/generated_samples_list.json, lib/samples/cut_geometry/README.metadata.json
Cherry picks a correction to Cut Geometry metadata that is going into `main` with the latest Beta 2 samples.
=> Cut Geometry correction

README.md
Cherry picks a doc update relating to API keys made directly to `main` into `v.next`.
=> Cherry pick doc update

lib/samples/query_related_features/query_related_features.dart
The scrolling in the detail pane was getting confused between the overall scroll view and the scrolling list views that were in the column. This PR addresses those issues.
- Preserve and species listings are no longer in ListViews. They are now just additional items in the column
- Park title is fixed at top of popup
- All other items are in a single scrolling view
=> Fix scrolling in Query Related Feature detail popup

lib/samples/generate_offline_map/generate_offline_map.dart
A small fix that hardcodes a minScale per another implementation and provides the default maxScale - so specifying the geometry, min and max scales are still met. Updated comments to emphasies this. In my testing this appears to resolve previously reported issues consistently. To me this still meets the aims of the sample and provides a more consistent result.
=> Generate Offline Map Fix

lib/samples/snap_geometry_edits/README.md, lib/samples/snap_geometry_edits/snap_geometry_edits.dart
- Adds the additional notes on haptics to the Snap Geometry Edits sample
- Amends the initial default value of the geometry guides (the default is saying false in the doc - not sure if this changed or was just a mistake initially). Then sets geometry guides on by default, along with snapping.
As an aside, have tested the haptics from this sample and works well.
=> Include haptics doc in Snap Geometry Edits sample

lib/main.dart, lib/utils/sample_runner.dart
Amends so that we better catch the API Key not being set to help with error messaging. Follows the way we have implemented in our example code.
=> Improve API Key workflow

assets/generated_samples_list.json, lib/samples/add_feature_layer_with_time_offset/README.metadata.json, lib/samples/add_map_image_layer/README.metadata.json, lib/samples/add_wfs_layer/README.md, lib/samples/style_graphics_with_renderer/README.md, lib/samples/style_graphics_with_renderer/README.metadata.json
After reviewing the samples directory on the developers site (where the metadata pulls through), I identified the following tidy ups:
- Some alterations to categories (they weren't specified clearly in the design repo)
- A fix to a broken image
- Correction to a partial description to match the design.
=> Sample tidy ups

lib/samples/identify_features_in_wms_layer/identify_features_in_wms_layer.dart
It is possible to tap twice and get two "identify" operations happening at the same time. The first one will present the info dialog properly, but the second will present a blank info dialog.
Here we flip `_ready` back to `false` during an identify to prevent extra taps.
=> Disable tapping while an identify operation is in progress

lib/samples/query_related_features/query_related_features.dart
Currently, while data is loading, the entire bottom sheet is replaced with a small progress indicator that sits under the safe area at the bottom of the screen. This change instead keeps the bottom sheet where it is, with the progress indicator taking up the location of just the title widget. This is a less jarring transition from one item to the next.
Most of the change is just whitespace from re-indenting the widget code.
=> Move the progress indicator to only replace the title widget

lib/common/theme_data.dart
The recent work on ThemeData should have kept `customWhiteStyle`. This resolves the build failure.
=> We still need customWhiteStyle

lib/samples/apply_symbology_to_shapefile/README.md
Toggle the switch to apply a new symbology renderer to the feature layer created from the shapefile.
=> Update "Apply symbology to Shapefile" sample's readme

.github/ISSUE_TEMPLATE/arcgis-maps-sdk-for-flutter-samples-issue-template.md
Adds an issue template to help define this repo as being for samples related issues so that SDK related issues or feature requests are driven to the Community Forum, or individual account managers. Also communicates the URL of the forum.
In addition, asks some initial questions that will help with any issues with the samples that do arise.
=> Add issue template

lib/samples/set_up_location_driven_geotriggers/set_up_location_driven_geotriggers.dart
The dialog showing the details of the features has been updated.
- List of multiple features has been replaced with viewing a single feature detail at a time with buttons to move between featrures
- image attachments are now displayed with the description text
- scrolling of the HTML description field works properly.
=> Improvement of the Geotrigger sample detail dialog

lib/samples/add_raster_from_file/add_raster_from_file.dart, lib/samples/identify_raster_cell/identify_raster_cell.dart
With a recent push, certain utility classes have moved to be exported from `common/common.dart`. The samples that were in flight at the time need to be updated with the new location.
=> Update the latest samples for the new location of util classes

lib/samples/authenticate_with_oauth/authenticate_with_oauth.dart, lib/samples/show_portal_user_info/show_portal_user_info.dart
As part of standardizing how we use widget `dispose()`, OAuth provides the most complex case. To log out properly, you need to call `revokeToken()`, which makes a network request to revoke the token on the server. This is necessarily both asynchronous and able to throw an exception. Since we don't want to use async/await in `dispose()`, we create a Future, let it run without `await`ing on it, and use `catchError()` to keep errors from escaping as unhandled exceptions.
In a real production environment, you would probably want to build a more elaborate mechanism that isn't tied to a specific widget. But I'm thinking we don't want to build that out in individual samples. With the simplified pattern we're showing here, at least it's clear that the client code is responsible for handling …
=> Clean up OAuth logout when dismissing a sample

lib/samples/set_basemap/set_basemap.dart
Sort the basemaps by name. This ensures that they will appear in the same order on every run, which is necessary for automation.
Note that the basemaps have to be loaded before we can access the name property, so those all have to be loaded before looping through them. Using "Future.wait" also ends up being more efficient, because the network requests are all initiated in parallel, rather than loading them one at a time.
=> Sort basemaps by name

lib/common/busy_indicator.dart, lib/samples/add_raster_from_service/add_raster_from_service.dart
Loading a raster layer from a service can take a long time. This PR adds a "Drawing..." popup to inform the user that the map is still working on rendering the layer.
**Summary of Changes**
- A new BusyIndicator widget was created and added to the common folder
- The BusyIndicator was applied to the Add raster from service sample
=> Add loading indicator for Add raster from service sample

pubspec.yaml
Cherry picking the update of the min version to `v.next` so we're up to date post-release.
=> Update arcgis_maps version minimum

lib/samples/animate_images_with_image_overlay/animate_images_with_image_overlay.dart
- Switch to cache the file URIs in the list, Image and ImageFrame need to be created each time.
- Change to the fast speed to 17 ms (post-frame updating animating image) as Qt sample
=> cs/Fix the crash for the image animations on the ImageOverlay

lib/samples/match_viewpoint_of_geo_views/README.md, lib/samples/match_viewpoint_of_geo_views/match_viewpoint_of_geo_views.dart
- Using GestureDetector to decide if one of the GeoViews needs to update the other one. It is more reliable than using the navigation point changed callback.
=> cs/Using gesture detector 

lib/samples/edit_with_branch_versioning/edit_with_branch_versioning.dart, lib/samples/generate_offline_map/generate_offline_map.dart, lib/samples/identify_features_in_wms_layer/identify_features_in_wms_layer.dart, lib/samples/match_viewpoint_of_geo_views/match_viewpoint_of_geo_views.dart, lib/samples/set_up_location_driven_geotriggers/set_up_location_driven_geotriggers.dart, lib/samples/show_legend/show_legend.dart, lib/utils/ripple_page_route.dart
`MediaQuery.of(context)` is inefficient (your widget will rebuild for every change to any property of `MediaQuery`). We should always use a more specific accessor, such as `MediaQuery.sizeOf(context)`.
=> Replace MediaQuery.of(context)

lib/samples/add_raster_from_service/add_raster_from_service.dart, lib/samples/apply_mosaic_rule_to_rasters/apply_mosaic_rule_to_rasters.dart, lib/samples/match_viewpoint_of_geo_views/match_viewpoint_of_geo_views.dart
A "late" variable that is accessed in the "dispose()" method must be created in "initState()" (or before). If it is created at some later time, such as in "onMapViewReady()", there is the possibility that "dispose()" will be called before the variable is created. That would cause an unhandled exception, crashing the app.
There are different ways to handle this, but here we change it from a "late" variable to a nullable variable, and then safely use it with the `?` operator in "dispose()".
=> Fix potential access of "late" variables

analysis_options.yaml, lib/models/sample.dart, lib/samples/edit_feature_attachments/edit_feature_attachments.dart, lib/samples/manage_features/manage_features.dart, lib/samples/query_related_features/query_related_features.dart, lib/samples/set_up_location_driven_geotriggers/set_up_location_driven_geotriggers.dart, lib/widgets/sample_viewer_page.dart
Turn on the "strict-casts" language mode to require ourselves to make casts explicit rather than implicitly casting from `dynamic`. Also adopt the other "analyzer/errors" settings we use internally.
This required several adjustments where we weren't following this rule, such as when working with JSON objects.
=> adopt "strict-casts" language mode

lib/samples/authenticate_with_oauth/README.md, lib/samples/authenticate_with_oauth/README.metadata.json, lib/samples/authenticate_with_oauth/authenticate_with_oauth.dart, lib/samples/authenticate_with_token/README.md, lib/samples/authenticate_with_token/README.metadata.json, lib/samples/authenticate_with_token/authenticate_with_token.dart, lib/samples/show_portal_user_info/show_portal_user_info.dart, pubspec.yaml
The "Authenticate with OAuth" and "Authenticate with Token" samples have been updated to use the "Authenticator" toolkit component. This removes a bunch of redundant code.
The "Show Portal User Info" sample is a bit of a special case -- it doesn't use an `ArcGISMapView`. Instead, it uses the Portal API to fetch some information, and then loads it in the UI with simple text fields. Looking at the Swift SDK version of this sample, it doesn't use the Authenticator component. I think that makes sense, because this sample is more about using those lower-level API calls. So we don't use an Authenticator component here either. But, it does make sense to use Authenticator's static functions to revoke the OAuth tokens and clear the credential store.
Lastly, as this requires the Sample Viewer to …
=> Update samples to use the toolkit Authenticator component

pubspec.yaml
Updating min version to the next release so that we can use artifactory internally more easily. This branch won't build as-is until the corresponding toolkit PR is merged and built, so that the toolkit dependency on arcgis_maps is also resolved to 300.
=> Update arcgis version

lib/samples/download_preplanned_map_area/download_preplanned_map_area.dart, lib/samples/group_layers_together/group_layers_together.dart, lib/samples/navigate_route/navigate_route.dart
We've identified `setState(() {})` as a practice to be avoided. Here we fix up 3 samples to eliminate the need to use `setState(() {})`.
- Navigate route: use simple member variables of the "State" class to track changes to "autoPanMode" and "started", then use those member variables in the "build()" method.
- Group layers together: rather than rebuilding the whole widget tree with every change, we can use "StreamBuilders" to listen to each Layer's "onVisibilityChanged" stream, then only rebuild the affected widgets.
- Download preplanned map areas: similar to the previous, but elaborated out more. Here we use a simple "model" object called "PreplannedEntry" to manage the state of each "PreplannedMapArea" and its associated download job, paired with a "PreplannedEntryListTile" widget that …
=> Refactor to avoid using setState with an empty body

analysis_options.yaml, lib/main.dart, lib/samples/animate_3d_graphic/animate_3d_graphic.dart, lib/samples/authenticate_with_oauth/authenticate_with_oauth.dart, lib/samples/create_mobile_geodatabase/create_mobile_geodatabase.dart, lib/samples/display_clusters/display_clusters.dart, lib/samples/download_preplanned_map_area/download_preplanned_map_area.dart, lib/samples/edit_feature_attachments/edit_feature_attachments.dart, lib/samples/edit_with_branch_versioning/edit_with_branch_versioning.dart, lib/samples/find_route/find_route.dart, lib/samples/find_route_in_mobile_map_package/find_route_in_mobile_map_package.dart, lib/samples/identify_features_in_wms_layer/identify_features_in_wms_layer.dart, lib/samples/query_table_statistics/query_table_statistics.dart, lib/samples/set_up_location_driven_geotriggers/set_up_location_driven_geotriggers.dart, lib/samples/show_grid/show_grid.dart, lib/samples/show_portal_user_info/show_portal_user_info.dart, lib/utils/sample_skeleton.dart, lib/widgets/sample_info_popup_menu.dart, lib/widgets/sample_list_view.dart
The "strict-inference" language mode requires all inferred types to be unambiguous. This prompts us to understand the types of objects we're creating and makes our intent more explicit.
=> Adopt the "strict-inference" language mode

analysis_options.yaml, lib/builder.dart, lib/samples/add_raster_from_service/add_raster_from_service.dart, lib/samples/match_viewpoint_of_geo_views/match_viewpoint_of_geo_views.dart, lib/samples/set_basemap/set_basemap.dart, lib/samples/set_up_location_driven_geotriggers/set_up_location_driven_geotriggers.dart, lib/samples/show_device_location/show_device_location.dart, lib/samples/show_device_location_history/show_device_location_history.dart, lib/samples/show_device_location_with_nmea_data_sources/show_device_location_with_nmea_data_sources.dart, lib/samples/show_grid/show_grid.dart, lib/utils/ripple_page_route.dart
This "strict-raw-types" language mode disallows the use of raw generic types (i.e., using a generic type without type arguments). This requires us to specify the generic types, such as `Future` must now be `Future<dynamic>` or `Future<void>`, etc.
=> Adopt the "strict-raw-types" language mode

lib/main.dart, lib/router_config.dart, lib/sample_viewer_app.dart, lib/widgets/category_transition_page.dart, lib/widgets/code_view_page.dart, lib/widgets/readme_page.dart, lib/widgets/ripple_transition_page.dart, lib/widgets/sample_info_popup_menu.dart, lib/widgets/sample_list_view.dart, lib/widgets/sample_viewer_page.dart, pubspec.yaml
- Moved the main `SampleViewerApp` widget out to its own file
- Factored out the `allSamples` list from `SampleViewerApp` so that it can be used by the GoRouter configuration
- Implemented a GoRouter configuration in `router_config.dart`
- Replaced the existing `Navigator` calls with GoRouter calls
- Restructured the two custom page transition animations to work with GoRouter and put into their own files
- Added the README/Code/Website menu (`SampleInfoPopupMenu`) to the README and Code pages
- Adjusted `SampleInfoPopupMenu` to use GoRouter with some special logic to make sure we're not pushing multiple instances of the README and Code pages onto the navigation stack
=> Implement GoRouter for navigation

pubspec.yaml
Our new "LTS" branch should be configured to use 200.8.1.
=> Update lts branch to use 200.8.1

lib/main.dart, lib/widgets/sample_viewer_page.dart
We recently changed how we loaded sample data as part of implementing GoRouter. This caused a regression where the SampleViewerPage would read the sample data again and create duplicate entries for all the samples. So here we remove the redundant loading.
We also make the sample list "unmodifiable" so that it will throw an exception if this sort of thing happens again. Plus, now that SampleViewerPage no longer has to do the asynchronous work of loading the samples, we can remove the "post frame callback" and the "_ready" state.
=> Only load sample data once

ios/Flutter/AppFrameworkInfo.plist, pubspec.yaml
Upgrade to Flutter 3.35.2 (and Dart 3.9.0). Flutter automatically upgrades our build configuration from iOS 12 to 13.
=> Upgrade to Flutter 3.35.2
