Esri/arcgis-maps-sdk-flutter-samples

- analysis_options.yaml
- lib/samples/add_feature_collection_layer_from_table/add_feature_collection_layer_from_table_sample.dart
- lib/samples/add_feature_layers/add_feature_layers_sample.dart
- lib/samples/add_tiled_layer/add_tiled_layer_sample.dart
- lib/samples/add_tiled_layer_as_basemap/add_tiled_layer_as_basemap_sample.dart
- lib/samples/add_vector_tiled_layer/add_vector_tiled_layer_sample.dart
- lib/samples/apply_class_breaks_renderer_to_sublayer/apply_class_breaks_renderer_to_sublayer_sample.dart
- lib/samples/apply_scheduled_updates_to_preplanned_map_area/apply_scheduled_updates_to_preplanned_map_area_sample.dart
- lib/samples/apply_simple_renderer_to_feature_layer/apply_simple_renderer_to_feature_layer_sample.dart
- lib/samples/apply_unique_value_renderer/apply_unique_value_renderer_sample.dart
- lib/samples/authenticate_with_oauth/authenticate_with_oauth_sample.dart
- lib/samples/display_clusters/display_clusters_sample.dart
- lib/samples/display_map/display_map_sample.dart
- lib/samples/display_map_from_mobile_map_package/display_map_from_mobile_map_package_sample.dart
- lib/samples/download_preplanned_map_area/download_preplanned_map_area_sample.dart
- lib/samples/filter_by_definition_expression_or_display_filter/filter_by_definition_expression_or_display_filter_sample.dart
- lib/samples/find_address_with_reverse_geocode/find_address_with_reverse_geocode_sample.dart
- lib/samples/find_closest_facility_from_point/find_closest_facility_from_point_sample.dart
- lib/samples/find_route/find_route_sample.dart
- lib/samples/identify_layer_features/identify_layer_features_sample.dart
- lib/samples/query_feature_table/query_feature_table_sample.dart
- lib/samples/query_table_statistics/query_table_statistics_sample.dart
- lib/samples/search_with_geocode/search_with_geocode_sample.dart
- lib/samples/select_features_in_feature_layer/select_features_in_feature_layer_sample.dart
- lib/samples/show_device_location/show_device_location_sample.dart
- lib/samples/show_device_location_history/show_device_location_history_sample.dart
- lib/samples/show_magnifier/show_magnifier_sample.dart
- lib/samples/show_service_area/show_service_area_sample.dart
- lib/samples/style_point_with_simple_marker_symbol/style_point_with_simple_marker_symbol_sample.dart
- lib/utils/sample_runner.dart
https://devtopia.esri.com/runtime/flutter/issues/1765
Adopted and applied linter rule "directives_ordering" for the samples app.
> Shokhina toj/1765 directives ordering lint

- .gitignore
- README.md
- android/app/src/main/jniLibs/arm64-v8a/libarcgis_maps_ffi.so
- android/app/src/main/jniLibs/arm64-v8a/libruntimecore.so
- android/app/src/main/jniLibs/x86_64/libarcgis_maps_ffi.so
- android/app/src/main/jniLibs/x86_64/libruntimecore.so
Special Windows-only instructions for cloning the repo and for running `dart run arcgis_maps install`.
> Instructions for using Windows as host

- lib/samples/style_point_with_simple_marker_symbol/style_point_with_simple_marker_symbol_sample.dart
Small correction to Simple Marker Symbol sample.
> Simple Marker Symbol update

- lib/samples/add_feature_layers/README.md
Needed to revisit this sample to update the README - it had missing carriage returns
> Add feature layers sample

- lib/samples/filter_by_definition_expression_or_display_filter/filter_by_definition_expression_or_display_filter_sample.dart
Made changes to the button names so they match common sample
> Filter by definition expression or display filter Sample

- lib/samples/filter_by_definition_expression_or_display_filter/README.md
Applied suggested change to the sentence in README.
> Filter by definition expression or display filter

- lib/samples/add_vector_tiled_layer/README.md
Need some backticks to properly format API references in the README.
> Formatting in "Add Vector Tiled Layer" readme

- lib/main.dart
- lib/samples/add_feature_layers/add_feature_layers_sample.dart
- lib/samples/add_tiled_layer/add_tiled_layer_sample.dart
- lib/samples/add_tiled_layer_as_basemap/add_tiled_layer_as_basemap_sample.dart
- lib/samples/add_vector_tiled_layer/add_vector_tiled_layer_sample.dart
- lib/samples/apply_class_breaks_renderer_to_sublayer/apply_class_breaks_renderer_to_sublayer_sample.dart
- lib/samples/apply_scheduled_updates_to_preplanned_map_area/apply_scheduled_updates_to_preplanned_map_area_sample.dart
- lib/samples/apply_simple_renderer_to_feature_layer/apply_simple_renderer_to_feature_layer_sample.dart
- lib/samples/apply_unique_value_renderer/apply_unique_value_renderer_sample.dart
- lib/samples/display_clusters/display_clusters_sample.dart
- lib/samples/display_map/display_map_sample.dart
- lib/samples/display_map_from_mobile_map_package/display_map_from_mobile_map_package_sample.dart
- lib/samples/filter_by_definition_expression_or_display_filter/filter_by_definition_expression_or_display_filter_sample.dart
- lib/samples/find_address_with_reverse_geocode/find_address_with_reverse_geocode_sample.dart
- lib/samples/find_route/find_route_sample.dart
- lib/samples/query_feature_table/query_feature_table_sample.dart
- lib/samples/show_grid/show_grid_sample.dart
- lib/samples/show_service_area/show_service_area_sample.dart
- lib/samples/style_point_with_simple_marker_symbol/style_point_with_simple_marker_symbol_sample.dart
- lib/utils/sample_data.dart
- lib/utils/sample_runner.dart
- tool/generate_samples_list.dart
- tool/readme_scripts/readme_scripts_runner.dart
This PR updates comments only (no code changes). Applies a consistent pattern across the existing samples to carry forward.
> Apply comment format across samples

- lib/main.dart
- lib/models/sample.dart
Adding search bar to the main sample viewer screen
> Search functionality 

- lib/samples/edit_feature_attachments/README.md
Update README
https://devtopia.esri.com/runtime/flutter/issues/1558#issuecomment-4888544
> cs/Update the README of Edit Feature Attachment

- lib/samples/create_planar_and_geodetic_buffers/create_planar_and_geodetic_buffers_sample.dart
Fixes a warning about import ordering.
> Import fix

- lib/samples/authenticate_with_token/README.md
- lib/samples/show_device_location/README.md
- Missed the hyperlink on the "Traffic web map" in a README
- "Re-Center" changed to "Recenter" in a README
> Cosmetic fixes

- lib/samples/create_mobile_geodatabase/create_mobile_geodatabase_sample.dart
update a Runtime text:
https://devtopia.esri.com/runtime/flutter/issues/1560#issuecomment-4894080
> "create mobile geodatabase" update

- lib/samples/create_planar_and_geodetic_buffers/create_planar_and_geodetic_buffers_sample.dart
- lib/samples/densify_and_generalize_geometry/densify_and_generalize_geometry_sample.dart
- lib/samples/manage_bookmarks/manage_bookmarks_sample.dart
- lib/samples/query_table_statistics/query_table_statistics_sample.dart
- lib/samples/show_device_location/show_device_location_sample.dart
Everywhere we use "bottomSheet" now has 20.0 top padding, no specified background color, and "titleLarge" TextStyle.
> Unify styling of bottom sheets

- lib/models/samples_widget_list.dart
- lib/samples/download_vector_tiles_to_local_cache/download_vector_tiles_to_local_cache.dart
`flutter analyze` picked up a few things
> Clear some warnings

- lib/samples/query_table_statistics/query_table_statistics.dart
- lib/samples/set_basemap/set_basemap.dart
- lib/samples/show_device_location_history/show_device_location_history.dart
Completes the task of doing a sweep of samples where the common design was recently applied, to identify any minor coding standard/pattern tidy ups that weren't the focus of those reviews and/or areas where code wasn't updated.
> Sample tidy ups

- lib/models/samples_widget_list.dart
- lib/samples/cut_geometry/cut_geometry.dart
> Rename cut geometry sample

- tool/generate_new_sample.dart
The new analyzer settings need to be applied to the recent generate_new_sample.dart file.
> Apply analyzer fixes to generate_new_sample.dart

- lib/samples/set_reference_scale/README.md
The README wasn't clear about the scrolling feature of the settings dialog (not everything fits into it without scrolling feature)
> Updated set scale sample README

- pubspec.yaml
I missed the most important one
> Update to the new package name

- lib/samples/densify_and_generalize_geometry/densify_and_generalize_geometry.dart
point and part collections now have iterators, so we can use `for ... in` loops
> Use the new iterators

- lib/samples/create_mobile_geodatabase/create_mobile_geodatabase.dart
- lib/samples/filter_by_definition_expression_or_display_filter/filter_by_definition_expression_or_display_filter.dart
- lib/samples/query_feature_table/query_feature_table.dart
Match the upcoming change in the API to rename "parameters" to "queryParameters"
> Change "parameters" to "queryParameters"

- lib/samples/edit_feature_attachments/edit_feature_attachments.dart
- lib/samples/query_feature_table/query_feature_table.dart
- lib/samples/query_related_features/query_related_features.dart
- lib/samples/select_features_in_feature_layer/select_features_in_feature_layer.dart
- lib/samples/set_reference_scale/set_reference_scale.dart
Update samples to follow recent changes in the API regarding naming parameters.
> Some parameters are now positional

- assets/generated_samples_list.json
- lib/samples/add_feature_layers/README.md
- lib/samples/add_feature_layers/README.metadata.json
- lib/samples/identify_features_in_wms_layer/README.metadata.json
- Adds shapefile to readme for Add Feature Layers
- Cleans up metadata
> Sample clean ups

- lib/samples/densify_and_generalize_geometry/densify_and_generalize_geometry.dart
Update to adjust for recent changes to constructors taking a nullable SpatialReference
> API change to MutablePointCollection constructor

- lib/samples/add_feature_layers/README.md
Seems these i/ii needed extra spaces to render right.
> Add spaces to readme

- lib/samples/add_feature_layers/README.md
Another catch by Kathleen. Need to add the shapefile URL. Note it loads for me (she gets 403 but known issue).
> Add shapefile url

- ios/Runner/AppDelegate.swift
- pubspec.yaml
Changes to keep up with the upgrade to Flutter 4.24.3
> Upgrade to Flutter 3.24.3

- lib/samples/add_feature_collection_layer_from_table/add_feature_collection_layer_from_table.dart
- lib/samples/cut_geometry/cut_geometry.dart
- lib/samples/densify_and_generalize_geometry/densify_and_generalize_geometry.dart
- lib/samples/identify_graphics/identify_graphics.dart
- lib/samples/show_device_location_history/show_device_location_history.dart
We updated the constructors for classes that derive from GeometryBuilder.
> Update to follow changes to "Builder" constructors

- lib/samples/create_mobile_geodatabase/create_mobile_geodatabase.dart
- lib/samples/download_preplanned_map_area/download_preplanned_map_area.dart
- lib/samples/filter_by_definition_expression_or_display_filter/filter_by_definition_expression_or_display_filter.dart
- lib/samples/find_address_with_reverse_geocode/find_address_with_reverse_geocode.dart
- lib/samples/find_closest_facility_from_point/find_closest_facility_from_point.dart
- lib/samples/find_route/find_route.dart
- lib/samples/query_feature_table/query_feature_table.dart
- lib/samples/query_table_statistics/query_table_statistics.dart
- lib/samples/show_service_area/show_service_area.dart
Certain named parameters are becoming positional parameters.
> Follow API updates to shorten parameters

- lib/samples/filter_by_definition_expression_or_display_filter/filter_by_definition_expression_or_display_filter.dart
- lib/samples/manage_bookmarks/manage_bookmarks.dart
My previous PR missed some of the shortened parameters
> Some more shortened parameters

- assets/generated_samples_list.json
- lib/samples/display_dimensions/README.md
- lib/samples/edit_feature_attachments/README.md
- lib/samples/query_related_features/README.md
- lib/samples/query_related_features/README.metadata.json
- lib/samples/show_device_location/README.metadata.json
- lib/samples/show_device_location_history/README.md
- lib/samples/show_grid/README.md
I wanted to double check existing samples were in good order to aid new colleagues. I ran the readme checker script on all samples (this is currently in a separate branch following sprint x work and isn't a priority for review so leaving it there for now https://github.com/Esri/arcgis-maps-sdk-flutter-samples/tree/jen/readme_scripts_all_samples).
That output the following failures which I've cleaned up and all checks pass.
> Readme clean ups

- lib/samples/add_feature_layers/add_feature_layers.dart
- With the changes of named parameters of factory method : `FeatureLayer.withItem(item, Int)`, the sample need to update,
> update the featurelayer withItem

- assets/generated_samples_list.json
- lib/models/samples_widget_list.dart
Fixed the issue with JSON preventing the app to run
> Json Fix to run the app

- lib/samples/manage_features/manage_features.dart
From verification feedback, deselects feature on geometry update.
> Manage features update

- README.md
- pubspec.yaml
Configure pubspec.yaml to use pub.dev and update the readme
> Set up for use with pub.dev

- lib/samples/download_vector_tiles_to_local_cache/download_vector_tiles_to_local_cache.dart
- Adds a SnackBar for notification when the download is finished
> cs/Adds a SnackBar notification

- lib/samples/show_service_area/show_service_area.dart
- Adds a try/catch to catch the exception and prompt to the users
> cs/Adds a try-catch to prompt user errors

- lib/samples/create_mobile_geodatabase/create_mobile_geodatabase.dart
-avoid the text overflow on certain device.
> cs/Update the Sample Create Mobile Geodatabase

- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- android/settings.gradle
- Upgrade the Gradle and AGP version
> cs/Upgrade the Gradle and AGP versions

- lib/samples/download_vector_tiles_to_local_cache/download_vector_tiles_to_local_cache.dart
Let the progress bar staying for 5 seconds once it finished.
> Cs/2575 - improve UI experience for progress bar

- lib/builder.dart
Some recent code missed its `dart format`.
> Catch a `dart format` change

- lib/samples/apply_symbology_to_shapefile/apply_symbology_to_shapefile.dart
This sample was developed parallel to the big lint-fixing PR, so it didn't get all the lint checks. Just a few changes are necessary to resolve the analyzer warnings.
> Some lint fixes that were missed in passing

- lib/samples/edit_with_branch_versioning/README.metadata.json
Updated the category from *Edit* to *Edit and Manage Data*
> Edit Branch Versioning updated category

- .github/ISSUE_TEMPLATE/arcgis-maps-sdk-for-flutter-samples-issue-template.md
Need to remove the comment as formatting impacting the issue template.
> Remove comment from issue template

- android/app/build.gradle
We are updating the build.gradle to the latest Android NDK. The app runs without any crashes on Android.
> Update Android NDK

- android/.gitignore
- ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- pubspec.yaml
Move up to Flutter 3.29 (Dart 3.7).
> Build with Flutter 3.29

- pubspec.yaml
Update our 3rd-party dependences to their latest versions
> Updates to 3rd-party dependencies

- lib/samples/apply_mosaic_rule_to_rasters/apply_mosaic_rule_to_rasters.dart
- show a running spinner when the mosaic rule is changed(since it take a time)
- follow the design to apply the different operation
> Cs/Mosaic Rule Sample followup

- lib/samples/apply_mosaic_rule_to_rasters/apply_mosaic_rule_to_rasters.dart
- lib/samples/create_and_edit_geometries/create_and_edit_geometries.dart
Changes made by running `dart format .`. One inserted comma and a bunch of whitespace changes.
> Changes made by "dart format"

- lib/samples/display_scene/display_scene.dart
We have renamed the Camera constructors, including this one.
> shorten camera constructor name

- lib/samples/animate_3d_graphic/animate_3d_graphic.dart
The modal bottom sheet was using `StatefulBuilder` but wasn't being notified when the parent widget's `_progress` value changed. The `_onTick` method was calling `setState()` on the main widget, but the modal sheet remained static until manually refreshed.
- Added modal state tracking with `_isMissionModalOpen` flag and `_modalStateSetter` reference
- Modified `_onTick` method to update the modal sheet state when animation is playing and modal is open
> Real-time progress bar updates in mission settings modal

- lib/models/sample.dart
- lib/samples/display_clusters/display_clusters.dart
- lib/samples/show_grid/show_grid.dart
Following up from the previous change to enable "strict casts", I missed a few.
> A few more strict casts
